### ISSUE TITLE
package.json里面没有依赖iview或者view-design怎么验证呢

### ISSUE THREAD

**Issue by PengKezhu** [ShisiJu/i-view-ie#1]

**Comment by PengKezhu** [comment]
就是想看一下iview在IE上的兼容，我现在的项目iview在IE上不能兼容

**Comment by ShisiJu** [comment]
@PengKezhu 
抱歉 代码有问题  之前写别的东西用到了这个 repo
我之后改一下
按照文章中内容, 我在公司的项目中配置好了可以运行在IE9以上;
但是, 我之后又发现了 更好的处理方式;
在 babel中可以指定打包 npm 库 中的文件;

**Comment by PengKezhu** [comment]
谢谢 更新好了可以通知我一下吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Ju <notifications@github.com&gt;
发送时间: 2020年10月23日 19:51
收件人: ShisiJu/i-view-ie <i-view-ie@noreply.github.com&gt;
抄送: Kevin <330312471@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ShisiJu/i-view-ie] package.json里面没有依赖iview或者view-design怎么验证呢 (#1)





 
@PengKezhu
 抱歉 代码有问题  之前写别的东西用到了这个 repo
 我之后改一下
 按照文章中内容, 我在公司的项目中配置好了可以运行在IE9以上;
 但是, 我之后又发现了 更好的处理方式;
 在 babel中可以指定打包 npm 库 中的文件;

**Comment by ShisiJu** [comment]
@PengKezhu 
我提交了新的代码;  在IE9上试了一下, 没有报错; 
如果发现问题, 可以再提出来;  具体的说明写在了 Readme里
